Unit kbXXX;

interface

Const
 kbCtrlA = $1E01;
 kbCtrlB = $3002;
 kbCtrlC = $2E03;
 kbCtrlD = $2004;
 kbCtrlE = $1205;
 kbCtrlF = $2106;
 kbCtrlG = $2207;
 kbCtrlH = $2308;
 kbCtrlI = $1709;
 kbCtrlJ = $240A;
 kbCtrlK = $250B;
 kbCtrlL = $260C;
 kbCtrlM = $320D;
 kbCtrlN = $310E;
 kbCtrlO = $180F;
 kbCtrlP = $1910;
 kbCtrlQ = $1011;
 kbCtrlR = $1312;
 kbCtrlS = $1F13;
 kbCtrlT = $1414;
 kbCtrlU = $1615;
 kbCtrlV = $2F16;
 kbCtrlW = $1117;
 kbCtrlX = $2D18;
 kbCtrlY = $1519;
 kbCtrlZ = $2C1A;

 kbGrayStar = $372A;

 kbClearShiftState = $000F;

var
 ShiftState: Byte absolute $40:$17;

implementation

End.

