(**********************************************************)
(*                                                        *)
(* Интегратор "Packet"                                    *)
(*                                                        *)
(* Модуль StreamId                                        *)
(* Константы номеров объектов в потоках                   *)
(*                                                        *)
(* Автор : Константин Вулах                               *)
(* Copyright (C) 1994 by VULCAN                           *)
(*                                                        *)
(* Начат         : 21.02.1994                             *)
(*                                                        *)
(**********************************************************)

unit StreamId;

interface

const

   idConfig           = 1000;
   idFileItem         = 1001;
   idSubDirItem       = 1002;
   idUpDirItem        = 1003;
   idArchItem         = 1004;
   idDirWindow        = 1005;
   idDirectoryBox     = 1006;
   idSubDir           = 1007;
   idItemsCollection  = 1008;
   idDirHandler       = 1009;
   idDirConfig        = 1010;
   idPathStack        = 1011;
   idPathItem         = 1012;
   idTextResource     = 1013;
   idAnnWindow        = 1014;
   idAnnViewer        = 1015;
   idHotKeyRef        = 1016;
   idCalendarView     = 1017;
   idCalendarWindow   = 1018;
   idCalcDisplay      = 1019;
   idCalculator       = 1020;
   idTable            = 1021;
   idReport           = 1022;
   idAsciiChart       = 1023;
   idDirWinIndicator  = 1024;
   idClosedFile       = 1025;
   idClosedFilesColl  = 1026;
   idOutputWindow     = 1027;
   idOutputInterior   = 1028;
   idStrStack         = 1029;
   idStartDir         = 1030;
   idRndNameTpl       = 1031;

implementation

end.

